In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
a = np.array([1,4,5])

In [4]:
a[0]

1

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [7]:
a.dtype

dtype('int32')

In [9]:
a.dtype = 'int16'

In [10]:
a.dtype

dtype('int16')

In [22]:
d = np.array([3,2,1])
d

array([3, 2, 1])

In [27]:
d = np.array([d],dtype='int64')

In [29]:
w = np.array(d)

In [30]:
w

array([[3, 2, 1]], dtype=int64)

In [32]:
w.shape

(1, 3)

In [33]:
a = np.array([[1,2,3],[4,5,6]])

In [36]:
a[0,2],a[1,2]

(3, 6)

In [43]:
a[1,1:2:2]

array([5])

In [45]:
a[0,0]+a[0,1],a[1,0]+a[1,1]

(3, 9)

In [53]:
a[0:,0::2]

array([[1, 3],
       [4, 6]])

In [55]:
a[0:,2::]

array([[3],
       [6]])

In [56]:
a[0,2],a[1,2]

(3, 6)

In [57]:
a[0:,-1]

array([3, 6])

In [61]:
b = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]],[[11,21,31,41],[51,61,71,81]]])
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[11, 21, 31, 41],
        [51, 61, 71, 81]]])

In [66]:
b[0:,0:,-1]

array([[ 4,  8],
       [40, 80],
       [41, 81]])

In [67]:
np.sum(b[0:,0:,-1])

254

In [72]:
b[0,0,0:-1]

array([1, 2, 3])

In [73]:
b[0,0,-1] + b[0,1,-1]

12

In [74]:
b

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]],

       [[11, 21, 31, 41],
        [51, 61, 71, 81]]])

In [84]:
b[0,0:,-1],b[1,0:,1:3],b[2,0:,0]

(array([4, 8]),
 array([[20, 30],
        [60, 70]]),
 array([11, 51]))

In [86]:
np.sum(b[0,0:,-1]+b[1,0:,1:3]+b[2,0:,0])

328

In [87]:
b[0,0:,-1]+b[1,0:,1:3]+b[2,0:,0]

array([[ 35,  89],
       [ 75, 129]])

In [89]:
n = np.array([[1,2,3],[4,5,6]])
n

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
n[0:,1]=10

In [91]:
n

array([[ 1, 10,  3],
       [ 4, 10,  6]])

In [92]:
n[0:,0::2]=3

In [93]:
n

array([[ 3, 10,  3],
       [ 3, 10,  3]])

In [104]:
z = np.zeros((2,2,3))

In [105]:
z

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [110]:
one = np.ones((3,3))

In [111]:
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [114]:
one[2]=[3,2,5]

In [115]:
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [3., 2., 5.]])

In [117]:
del one

In [120]:
a = np.full((2,2),3)

In [121]:
a

array([[3, 3],
       [3, 3]])

In [122]:
b = np.full(a.shape,1)

In [123]:
b

array([[1, 1],
       [1, 1]])

In [124]:
c = np.full_like(a,6)

In [125]:
c

array([[6, 6],
       [6, 6]])

In [127]:
d = np.full((3,5),3)

In [128]:
d

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [144]:
d = np.full_like((3,6,9),2)

In [145]:
b = np.full_like(c,70)

In [147]:
w = np.full_like([[1,2],[3,4]],90)

In [149]:
d = np.full_like(((1,2),(4,5)),2)

In [150]:
d

array([[2, 2],
       [2, 2]])

In [157]:
q = np.random.randint(2,6,10) # randint(start,end,number of numbers)

In [158]:
q

array([3, 4, 3, 3, 4, 3, 2, 3, 4, 3])

In [162]:
q = np.random.rand(2,9,3) # rand(size,size,size)

In [163]:
q

array([[[0.8752387 , 0.34978715, 0.56553498],
        [0.82550461, 0.28501747, 0.28963993],
        [0.60738439, 0.93531723, 0.03800369],
        [0.33156552, 0.52048562, 0.62390996],
        [0.61146738, 0.07103007, 0.07234394],
        [0.24710491, 0.41852117, 0.16426596],
        [0.57044414, 0.04973314, 0.47408992],
        [0.90001034, 0.59499745, 0.10093743],
        [0.76928932, 0.47954043, 0.69593569]],

       [[0.30276477, 0.99854882, 0.87088135],
        [0.22055501, 0.23752155, 0.63495311],
        [0.54686207, 0.66827242, 0.12209874],
        [0.18246938, 0.64765797, 0.37121029],
        [0.07234136, 0.25802577, 0.22190889],
        [0.4770639 , 0.32348327, 0.17133097],
        [0.02036381, 0.77166848, 0.4590708 ],
        [0.48822085, 0.89547178, 0.84577634],
        [0.96364683, 0.95500671, 0.19013439]]])

In [166]:
e = np.random.randint(2,10,(4,4))

In [167]:
e

array([[4, 8, 6, 9],
       [3, 2, 4, 7],
       [9, 6, 6, 2],
       [7, 6, 6, 6]])

In [171]:
c = np.random.choice([1,2,3,4,6])

In [172]:
c

3

In [173]:
i = np.identity(3)

In [174]:
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [177]:
i.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [178]:
n = np.array([[1,2,3],[4,5,6]])

In [179]:
n

array([[1, 2, 3],
       [4, 5, 6]])

In [189]:
a = np.repeat(n,2) # repeat(array,how times repeat, axis: 0=row,1=column)

In [190]:
b = np.repeat(n,2,axis=1)

In [192]:
b

array([[1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6]])

In [202]:
m = w

In [203]:
m[0]=[3,5]

In [204]:
m

array([[ 3,  5],
       [90, 90]])

In [211]:
w[1]=[6,10]

In [207]:
np.sin(m)

array([[ 0.14112001, -0.95892427],
       [ 0.89399666,  0.89399666]])

In [208]:
m*w # multipal the numbers

array([[   9,   25],
       [8100, 8100]])

In [209]:
np.matmul(m,w) # multipal the numbers base on matrix multipliction

array([[ 459,  465],
       [8370, 8550]])

In [213]:
m

array([[ 3,  5],
       [ 6, 10]])

In [214]:
w

array([[ 3,  5],
       [ 6, 10]])

In [218]:
q = np.array([[1,0],[7,11]])
q

array([[ 1,  0],
       [ 7, 11]])

In [219]:
w

array([[ 3,  5],
       [ 6, 10]])

In [220]:
q&w # and(&) returns the small numbers

array([[ 1,  0],
       [ 6, 10]])

In [221]:
q|w # or(|) returns ths big numbers

array([[ 3,  5],
       [ 7, 11]])

In [223]:
q@w

array([[  3,   5],
       [ 87, 145]])

In [222]:
np.linalg.det(q) # find the determinant

11.000000000000002

In [224]:
q

array([[ 1,  0],
       [ 7, 11]])

In [225]:
q>8

array([[False, False],
       [False,  True]])

In [226]:
q[q>8]

array([11])

In [227]:
np.max(q)

11

In [228]:
np.min(q)

0

In [229]:
np.sum(q,axis=1)

array([ 1, 18])

In [230]:
np.sum(q)

19

In [231]:
np.sum(q,axis=0)

array([ 8, 11])

In [232]:
q.reshape(4,1)

array([[ 1],
       [ 0],
       [ 7],
       [11]])

In [235]:
np.vstack((q,w))

array([[ 1,  0],
       [ 7, 11],
       [ 3,  5],
       [ 6, 10]])

In [236]:
np.hstack((q,w))

array([[ 1,  0,  3,  5],
       [ 7, 11,  6, 10]])

In [240]:
np.concatenate((w,q))

array([[ 3,  5],
       [ 6, 10],
       [ 1,  0],
       [ 7, 11]])

In [241]:
np.concatenate((w,q),axis=1)

array([[ 3,  5,  1,  0],
       [ 6, 10,  7, 11]])

In [242]:
np.all(q>w)

False

In [243]:
np.any(q>w)

True